/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Jdialog_GT_DN;

import DAO.TaiKhoanDAO;
import Helper.DialogHelper;
import Helper.ShareHelper;
import Main.Main;
import Model.TaiKhoan;
import QuanLi.DangKy;
import QuanLi.QuenMatKhau_1;
import java.awt.Color;
import java.awt.Frame;



/**
 *
 * @author Admin
 */
public class Login extends javax.swing.JFrame {
    
     TaiKhoanDAO tkDAO = new TaiKhoanDAO();
    
    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();
        init();
       
    }
    
    public void init(){
        this.setIconImage(ShareHelper.APP_ICON);
        
        this.setTitle("CHI TIÊU HÀNG NGÀY");
        lblHide.setVisible(false);
        tatMoDialog();

    }
    
     public void tatMoDialog(){
        new Loading(this,true).setVisible(true);
        
        
    }
    
    public boolean check() {
        if(Helper.checkHelper.checkNullText(txtlUsername) && Helper.checkHelper.checkNullPass(txtPass)){
            return true;
        }
        else{
        return false;
        }
    }
     
    public void login(){
        String userName =txtlUsername.getText();
        String matKhau = new String(txtPass.getPassword());

        try {
            
            TaiKhoan taikhoan = tkDAO.findById(userName);
             
                
                        if(taikhoan != null){
                            String matKhau2 = taikhoan.getMatKhau();
                            if(matKhau.equals(matKhau2)){
                                ShareHelper.USER = taikhoan;
                                DialogHelper.alert(this, "Đăng nhập thành công");
                                this.dispose();
                               new Main().setVisible(true);
                               
                            }
                            else{
                                DialogHelper.alert(this, "Sai mật khẩu!");
                                txtPass.setBackground(Color.red);
                                txtPass.requestFocus();
                            }
                        }
                        else{
                            DialogHelper.alert(this, "Sai tên đăng nhập");
                            txtlUsername.setBackground(Color.red);
                            txtlUsername.requestFocus();
                        }
        } catch (Exception e) {
            
        }
    }
    
    public void close(){
         DialogHelper.alert(this, "Cám ơn đã sử dụng phần mềm! \n Chúc bạn một ngày tốt lành!!");
            System.exit(0);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        panelLeft = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelRight = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtlUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnDangKy = new javax.swing.JButton();
        btnDangNhap = new javax.swing.JButton();
        lblQuenMK = new javax.swing.JLabel();
        lblShow = new javax.swing.JLabel();
        lblHide = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setPreferredSize(new java.awt.Dimension(650, 350));

        panelLeft.setPreferredSize(new java.awt.Dimension(325, 317));
        panelLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AnhBia23.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setOpaque(true);
        panelLeft.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 360));

        panelRight.setBackground(new java.awt.Color(199, 229, 245));
        panelRight.setPreferredSize(new java.awt.Dimension(325, 350));
        panelRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(13, 113, 180));
        lblUsername.setText("Tài khoản");
        panelRight.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 76, -1, -1));

        lblPass.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lblPass.setForeground(new java.awt.Color(13, 113, 180));
        lblPass.setText("Mật khẩu");
        panelRight.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 162, -1, -1));

        txtlUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtlUsername.setForeground(new java.awt.Color(204, 204, 204));
        txtlUsername.setText("Nhập Email hoặc Tài khoản");
        txtlUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtlUsernameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtlUsernameMouseExited(evt);
            }
        });
        txtlUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlUsernameActionPerformed(evt);
            }
        });
        panelRight.add(txtlUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 73, 180, 30));

        txtPass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        panelRight.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, 30));

        btnDangKy.setBackground(new java.awt.Color(23, 255, 139));
        btnDangKy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangKy.setForeground(new java.awt.Color(255, 255, 255));
        btnDangKy.setText("Đăng ký");
        btnDangKy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });
        panelRight.add(btnDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 211, -1, 40));

        btnDangNhap.setBackground(new java.awt.Color(13, 126, 255));
        btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        panelRight.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 211, -1, 40));

        lblQuenMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQuenMK.setForeground(new java.awt.Color(13, 113, 180));
        lblQuenMK.setText("Quên mật khẩu?");
        lblQuenMK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuenMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuenMKMouseClicked(evt);
            }
        });
        panelRight.add(lblQuenMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 269, -1, 27));

        lblShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/eye_open.png"))); // NOI18N
        lblShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblShowMousePressed(evt);
            }
        });
        panelRight.add(lblShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        lblHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blind_eye.png"))); // NOI18N
        lblHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblHideMousePressed(evt);
            }
        });
        panelRight.add(lblHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(panelLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelRight, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(panelLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        // TODO add your handling code here:
        new DangKy().setVisible(true);
        
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        if(check()){
            
            login();
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void txtlUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlUsernameMouseEntered
        // TODO add your handling code here:
        txtlUsername.setForeground(Color.black);
        if(txtlUsername.getText().equalsIgnoreCase("Nhập Email hoặc Tài khoản")){
            txtlUsername.setText("");
        }
        
        
        
        
    }//GEN-LAST:event_txtlUsernameMouseEntered

    private void txtlUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlUsernameMouseExited
        // TODO add your handling code here:
        if(txtlUsername.getText().isEmpty()){
            txtlUsername.setForeground(new Color(109,109,109));
            txtlUsername.setText("Nhập Email hoặc Tài khoản");
        }
    }//GEN-LAST:event_txtlUsernameMouseExited

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void lblShowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowMousePressed
        // TODO add your handling code here:
        lblShow.setVisible(false);
        lblHide.setVisible(true);
        txtPass.setEchoChar('\u0000');
    }//GEN-LAST:event_lblShowMousePressed

    private void lblHideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHideMousePressed
        // TODO add your handling code here:
        lblShow.setVisible(true);
        lblHide.setVisible(false);
        txtPass.setEchoChar('\u25cf');
    }//GEN-LAST:event_lblHideMousePressed

    private void txtlUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlUsernameActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_formWindowClosing

    private void lblQuenMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMKMouseClicked
        // TODO add your handling code here:
        new QuenMatKhau_1().setVisible(true);
    }//GEN-LAST:event_lblQuenMKMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblHide;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblQuenMK;
    private javax.swing.JLabel lblShow;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtlUsername;
    // End of variables declaration//GEN-END:variables
}
