package pc02674.asmhoanchinh.common;

public enum PageType {
	ADMIN_PAGE,REPORT_CATEGORY_PAGE,REPORT_MONTH_PAGE,
	
SITE_HOME_PAGE, SITE_LOGIN_PAGE, SITE_SIGNUP_PAGE, SITE_CHANGE_PASSWORD_PAGE,

SITE_EDIT_PROFILE_PAGE, SITE_FORGOT_PASSWORD_PAGE, SITE_PRODUCT_DETAIL_PAGE,

SITE_FAVORITE_PAGE, SITE_CART_PAGE,SITE_HISTORY_BUY,SITE_ORDER,SITE_VH, 

SITE_VPP,SITE_DIF,TEST_PAGE,USERF_ADMIN_PAGE,USERT_ADMIN_PAGE,BOOKF_ADMIN_PAGE,

BOOKT_ADMIN_PAGE,TYPEBOOKF_ADMIN_PAGE,TYPEBOOKT_ADMIN_PAGE,CUSTOMERS_ADMIN_PAGE,

NXBT_ADMIN_PAGE, NXBF_ADMIN_PAGE, NCCF_ADMIN_PAGE, NCCT_ADMIN_PAGE, 

TACGIAT_ADMIN_PAGE, TACGIAF_ADMIN_PAGE, ORDER_ADMIN_PAGE, ORDER_DELETED_ADMIN_PAGE, 

ORDER_FORM_ADMIN_PAGE,VALIDATION_PAGE
}
